# Generated by Django 5.2.3 on 2025-07-13 23:23

import django.db.models.deletion
import regacademico.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=10, unique=True, validators=[regacademico.validators.validar_ci])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.CharField(max_length=5)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regacademico.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regacademico.materia')),
            ],
            options={
                'unique_together': {('alumno', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regacademico.inscripcion')),
            ],
        ),
    ]
